server {
    listen 80;
    server_name _;

    location /back-x/ {
        alias /usr/share/nginx/html/back-x/;
        try_files $uri $uri/ /back-x/index.html;
    }

    location ~* ^/back-x/fonts/(.+\.(ttf|woff|woff2|eot|otf))$ {
        alias /usr/share/nginx/html/back-x/fonts/$1;
        access_log off;
        expires 30d;
        add_header Access-Control-Allow-Origin *;
    }
}
