[uwsgi]
socket		= 127.0.0.1:8002
chdir		= /www/wwwroot/xxgcms/
wsgi-file	= /www/wwwroot/xxgcms/apps/wsgi.py
python-executable = /usr/bin/python3
processes	= 2
threads		= 8
chmod-socket	= 660
logfile-chmod	= 644
py-autoreload	= 1
vhost 		= false
master		= true
vacuum		= true
pidfile		= /var/run/uwsgi2.pid
daemonize	= /dev/null
log-maxsize	= 100000
disable-logging	= true
; daemonize = /var/log/uwsgi/xxgcms.log
; disable-logging = false
