#!/bin/bash
# 扩展 MYSQL_USER 权限：允许 init_db / 新增站点 创建 CMS 库及日常 DML/DDL
set -euo pipefail

APP_USER="${MYSQL_USER:?MYSQL_USER not set}"
CMS_DB="${XXGCMS_CMS_DB_NAME:-xxgai}"
SYS_DB="${MYSQL_DATABASE:-xxgcms}"

mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" <<EOSQL
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER,
      CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, TRIGGER, REFERENCES, RELOAD
ON *.* TO '${APP_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${SYS_DB}\`.* TO '${APP_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${CMS_DB}\`.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
