[uwsgi]
socket		= 127.0.0.1:8003
chdir		= /www/wwwroot/xxgcms-web/www/
wsgi-file	= /www/wwwroot/xxgcms-web/www/apps/wsgi.py
python-executable = /usr/bin/python3
processes	= 2
threads		= 8
chmod-socket	= 660
logfile-chmod	= 644
py-autoreload	= 1
vhost 		= false
master		= true
vacuum		= true
pidfile		= /var/run/uwsgi-website.pid
daemonize	= /dev/null
log-maxsize	= 1000000
disable-logging	= true
